export const FEATURE_PRODUCT = [
  {
    id: 1001,
    name: 'Linen Dress',
    description:
      'Sportswear is no longer under culture, it is no longer indie or cobbled together as it once was. Sport is fashion today. The top is oversized in fit and style, may need to size down.',
    image: require('@assets/images/dress-5.png'),
    price: '$ 90.00',
    discount_price: '$ 52.00',
    color: ['black', 'brown', 'red'],
    size: ['XS', 'S', 'M', 'L', 'XL'],
    rating: {
      one_star: 80,
      two_star: 12,
      three_star: 5,
      four_star: 3,
      five_star: 0,
      average_rating: 4.5,
      total_ratings: 65,
    },
    ratings: [
      {
        id: 1,
        name: 'Jenifer Rose',
        image: require('@assets/images/rating-1.png'),
        rating: 5,
        message:
          'I love it.  Awesome customer service!! Helped me out with adding an additional item to my order. Thanks again!',
        date: 'Jan 23, 2024',
      },
      {
        id: 2,
        name: 'Kelly Rihana',
        image: require('@assets/images/rating-2.png'),
        rating: 5,
        message: "I'm very happy with order, It was delivered on and good quality. Recommended!",
        date: 'Jan 24, 2024',
      },
    ],
  },
  {
    id: 1002,
    name: 'Filted Waist Dress',
    description:
      'Sportswear is no longer under culture, it is no longer indie or cobbled together as it once was. Sport is fashion today. The top is oversized in fit and style, may need to size down.',
    image: require('@assets/images/dress-6.png'),
    price: '$ 82.00',
    discount_price: '$ 47.99',
    color: ['black', 'brown', 'red'],
    size: ['XS', 'S', 'M', 'L', 'XL'],
    rating: {
      one_star: 80,
      two_star: 12,
      three_star: 5,
      four_star: 3,
      five_star: 0,
      average_rating: 4.5,
      total_ratings: 65,
    },
    ratings: [
      {
        id: 1,
        name: 'Jenifer Rose',
        image: require('@assets/images/rating-1.png'),
        rating: 5,
        message:
          'I love it.  Awesome customer service!! Helped me out with adding an additional item to my order. Thanks again!',
        date: 'Jan 23, 2024',
      },
      {
        id: 2,
        name: 'Kelly Rihana',
        image: require('@assets/images/rating-2.png'),
        rating: 5,
        message: "I'm very happy with order, It was delivered on and good quality. Recommended!",
        date: 'Jan 24, 2024',
      },
    ],
  },
  {
    id: 1003,
    name: 'Maxi Dress',
    description:
      'Sportswear is no longer under culture, it is no longer indie or cobbled together as it once was. Sport is fashion today. The top is oversized in fit and style, may need to size down.',
    image: require('@assets/images/dress-7.png'),
    price: '$ 68.00',
    discount_price: '',
    color: ['black', 'brown', 'red'],
    size: ['XS', 'S', 'M', 'L', 'XL'],
    rating: {
      one_star: 80,
      two_star: 12,
      three_star: 5,
      four_star: 3,
      five_star: 0,
      average_rating: 4.5,
      total_ratings: 65,
    },
    ratings: [
      {
        id: 1,
        name: 'Jenifer Rose',
        image: require('@assets/images/rating-1.png'),
        rating: 5,
        message:
          'I love it.  Awesome customer service!! Helped me out with adding an additional item to my order. Thanks again!',
        date: 'Jan 23, 2024',
      },
      {
        id: 2,
        name: 'Kelly Rihana',
        image: require('@assets/images/rating-2.png'),
        rating: 5,
        message: "I'm very happy with order, It was delivered on and good quality. Recommended!",
        date: 'Jan 24, 2024',
      },
    ],
  },
  {
    id: 1004,
    name: 'Front Tie Mini Dress',
    description:
      'Sportswear is no longer under culture, it is no longer indie or cobbled together as it once was. Sport is fashion today. The top is oversized in fit and style, may need to size down.',
    image: require('@assets/images/dress-8.png'),
    price: '$ 59.00',
    discount_price: '',
    color: ['black', 'brown', 'red'],
    size: ['XS', 'S', 'M', 'L', 'XL'],
    rating: {
      one_star: 80,
      two_star: 12,
      three_star: 5,
      four_star: 3,
      five_star: 0,
      average_rating: 4.5,
      total_ratings: 65,
    },
    ratings: [
      {
        id: 1,
        name: 'Jenifer Rose',
        image: require('@assets/images/rating-1.png'),
        rating: 5,
        message:
          'I love it.  Awesome customer service!! Helped me out with adding an additional item to my order. Thanks again!',
        date: 'Jan 23, 2024',
      },
      {
        id: 2,
        name: 'Kelly Rihana',
        image: require('@assets/images/rating-2.png'),
        rating: 5,
        message: "I'm very happy with order, It was delivered on and good quality. Recommended!",
        date: 'Jan 24, 2024',
      },
    ],
  },
  {
    id: 1005,
    name: 'Ohara Dress',
    description:
      'Sportswear is no longer under culture, it is no longer indie or cobbled together as it once was. Sport is fashion today. The top is oversized in fit and style, may need to size down.',
    image: require('@assets/images/dress-9.png'),
    price: '$ 85.00',
    discount_price: '',
    color: ['black', 'brown', 'red'],
    size: ['XS', 'S', 'M', 'L', 'XL'],
    rating: {
      one_star: 80,
      two_star: 12,
      three_star: 5,
      four_star: 3,
      five_star: 0,
      average_rating: 4.5,
      total_ratings: 65,
    },
    ratings: [
      {
        id: 1,
        name: 'Jenifer Rose',
        image: require('@assets/images/rating-1.png'),
        rating: 5,
        message:
          'I love it.  Awesome customer service!! Helped me out with adding an additional item to my order. Thanks again!',
        date: 'Jan 23, 2024',
      },
      {
        id: 2,
        name: 'Kelly Rihana',
        image: require('@assets/images/rating-2.png'),
        rating: 5,
        message: "I'm very happy with order, It was delivered on and good quality. Recommended!",
        date: 'Jan 24, 2024',
      },
    ],
  },
  {
    id: 1006,
    name: 'Tie Back Mini Dress',
    description:
      'Sportswear is no longer under culture, it is no longer indie or cobbled together as it once was. Sport is fashion today. The top is oversized in fit and style, may need to size down.',
    image: require('@assets/images/dress-10.png'),
    price: '$ 67.00',
    discount_price: '',
    color: ['black', 'brown', 'red'],
    size: ['XS', 'S', 'M', 'L', 'XL'],
    rating: {
      one_star: 80,
      two_star: 12,
      three_star: 5,
      four_star: 3,
      five_star: 0,
      average_rating: 4.5,
      total_ratings: 65,
    },
    ratings: [
      {
        id: 1,
        name: 'Jenifer Rose',
        image: require('@assets/images/rating-1.png'),
        rating: 5,
        message:
          'I love it.  Awesome customer service!! Helped me out with adding an additional item to my order. Thanks again!',
        date: 'Jan 23, 2024',
      },
      {
        id: 2,
        name: 'Kelly Rihana',
        image: require('@assets/images/rating-2.png'),
        rating: 5,
        message: "I'm very happy with order, It was delivered on and good quality. Recommended!",
        date: 'Jan 24, 2024',
      },
    ],
  },
  {
    id: 1007,
    name: 'Leaves Green Dress',
    description:
      'Sportswear is no longer under culture, it is no longer indie or cobbled together as it once was. Sport is fashion today. The top is oversized in fit and style, may need to size down.',
    image: require('@assets/images/dress-11.png'),
    price: '$ 64.00',
    discount_price: '',
    color: ['black', 'brown', 'red'],
    size: ['XS', 'S', 'M', 'L', 'XL'],
    rating: {
      one_star: 80,
      two_star: 12,
      three_star: 5,
      four_star: 3,
      five_star: 0,
      average_rating: 4.5,
      total_ratings: 65,
    },
    ratings: [
      {
        id: 1,
        name: 'Jenifer Rose',
        image: require('@assets/images/rating-1.png'),
        rating: 5,
        message:
          'I love it.  Awesome customer service!! Helped me out with adding an additional item to my order. Thanks again!',
        date: 'Jan 23, 2024',
      },
      {
        id: 2,
        name: 'Kelly Rihana',
        image: require('@assets/images/rating-2.png'),
        rating: 5,
        message: "I'm very happy with order, It was delivered on and good quality. Recommended!",
        date: 'Jan 24, 2024',
      },
    ],
  },
  {
    id: 1008,
    name: 'Off Shoulder Dress',
    description:
      'Sportswear is no longer under culture, it is no longer indie or cobbled together as it once was. Sport is fashion today. The top is oversized in fit and style, may need to size down.',
    image: require('@assets/images/dress-12.png'),
    price: '$ 79.00',
    discount_price: '',
    color: ['black', 'brown', 'red'],
    size: ['XS', 'S', 'M', 'L', 'XL'],
    rating: {
      one_star: 80,
      two_star: 12,
      three_star: 5,
      four_star: 3,
      five_star: 0,
      average_rating: 4.5,
      total_ratings: 65,
    },
    ratings: [
      {
        id: 1,
        name: 'Jenifer Rose',
        image: require('@assets/images/rating-1.png'),
        rating: 5,
        message:
          'I love it.  Awesome customer service!! Helped me out with adding an additional item to my order. Thanks again!',
        date: 'Jan 23, 2024',
      },
      {
        id: 2,
        name: 'Kelly Rihana',
        image: require('@assets/images/rating-2.png'),
        rating: 5,
        message: "I'm very happy with order, It was delivered on and good quality. Recommended!",
        date: 'Jan 24, 2024',
      },
    ],
  },
];
